### ISSUE TITLE
Changing the color in the input does not update the swatch

### ISSUE THREAD

**Issue by sebastienb** [dcustodio/vue-native-color-picker#7]
Also if you set the color in your data on load the swatch ignores the value.

**Comment by dcustodio** [comment]
Hi @sebastienb I tried to reproduce it here: https://codesandbox.io/s/exciting-browser-sp2th?file=/src/App.vue
and it seems to work fine? can you share an example where it fails?

**Comment by Gaetitan** [comment]
Hi @dcustodio, I am experiencing the same issue.
The input works until the color picker is used. Once the color picker has been used to pick the color, the input will not work anymore.
I also reproduced it in your codesandbox.
### Steps to reproduce
1. Choose a color using the color picker.
2. Change the value in the input. **Color in the color picker is not updated**
### Expected behavior
The color should be updated in the color picker when changing the input.
